// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wedding_admin_cms.Persistance;

namespace wedding_admin_cms.Persistance.Migrations
{
    [DbContext(typeof(WeddingDbContext))]
    [Migration("20220127055327_MoreTables")]
    partial class MoreTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("wedding_admin_cms.Persistance.Entities.Entourage", b =>
                {
                    b.Property<Guid>("EntourageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("EntourageOfWeddingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleIdOfEntourage")
                        .HasColumnType("int");

                    b.HasKey("EntourageId");

                    b.HasIndex("EntourageOfWeddingId");

                    b.HasIndex("RoleIdOfEntourage")
                        .IsUnique();

                    b.ToTable("Entourages");
                });

            modelBuilder.Entity("wedding_admin_cms.Persistance.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("wedding_admin_cms.Persistance.Entities.Wedding", b =>
                {
                    b.Property<Guid>("WeddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Bride")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CeremonyDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CeremonyLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ReceptionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReceptionLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeddingId");

                    b.ToTable("Weddings");
                });

            modelBuilder.Entity("wedding_admin_cms.Persistance.Entities.Entourage", b =>
                {
                    b.HasOne("wedding_admin_cms.Persistance.Entities.Wedding", "Wedding")
                        .WithMany("Entourage")
                        .HasForeignKey("EntourageOfWeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wedding_admin_cms.Persistance.Entities.Role", "Role")
                        .WithOne("Entourage")
                        .HasForeignKey("wedding_admin_cms.Persistance.Entities.Entourage", "RoleIdOfEntourage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("wedding_admin_cms.Persistance.Entities.Role", b =>
                {
                    b.Navigation("Entourage");
                });

            modelBuilder.Entity("wedding_admin_cms.Persistance.Entities.Wedding", b =>
                {
                    b.Navigation("Entourage");
                });
#pragma warning restore 612, 618
        }
    }
}
