name: build & deploy frontend dev

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'        # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.404'             # set this to the .NET Core version to use

on:
  pull_request:
    branches: 
      - main
    paths: 
      - '**/wedding-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: cd ./src/wedding-frontend && dotnet build --configuration Release

      - name: dotnet publish
        run: cd ./src/wedding-frontend && dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/frontend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: ${{env.DOTNET_ROOT}}/frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Frontend'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: frontend-artifact

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.FRONTEND_WEBAPP_NAME }}-dev
          publish-profile: ${{ secrets.AZURE_WEBAPP_DEV_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: azure/appservice-settings@v1
        id: settings
        with:
          app-name: ${{ secrets.FRONTEND_WEBAPP_NAME }}-dev
          app-settings-json: '${{ secrets.FRONTEND_WEBAPP_APP_SETTINGS }}' 
          connection-strings-json: '${{ secrets.FRONTEND_WEBAPP_CONNECTION_STRINGS }}'
      - run: echo "The webapp-url is ${{ steps.settings.outputs.webapp-url }}"
      - run: |
          az logout
